imagePullSecrets:
  - name: ecr-registry

services:
  adminServer:
    name: admin-server
    image: 969799237091.dkr.ecr.eu-west-3.amazonaws.com/devops-petclinic/spring-petclinic-admin-server
    tag: latest
    containerPort: 9090

  apiGateway:
    name: api-gateway
    image: 969799237091.dkr.ecr.eu-west-3.amazonaws.com/devops-petclinic/spring-petclinic-api-gateway
    tag: latest
    containerPort: 8080
    replicas: 1

  configServer:
    name: config-server
    image: 969799237091.dkr.ecr.eu-west-3.amazonaws.com/devops-petclinic/spring-petclinic-config-server
    tag: latest
    containerPort: 8888
    replicas: 1


  customersService:
    name: customers-service
    image: 969799237091.dkr.ecr.eu-west-3.amazonaws.com/devops-petclinic/spring-petclinic-customers-service
    tag: latest
    containerPort: 8081
    replicas: 1


  discoveryServer:
    name: discovery-server
    image: 969799237091.dkr.ecr.eu-west-3.amazonaws.com/devops-petclinic/spring-petclinic-discovery-server
    tag: latest
    containerPort: 8761
    replicas: 1


  vetsService:
    name: vets-service
    image: 969799237091.dkr.ecr.eu-west-3.amazonaws.com/devops-petclinic/spring-petclinic-vets-service
    tag: latest
    containerPort: 8083
    replicas: 1


  visitsService:
    name: visits-service
    image: 969799237091.dkr.ecr.eu-west-3.amazonaws.com/devops-petclinic/spring-petclinic-visits-service
    tag: latest
    containerPort: 8082
    replicas: 1

