apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server
spec:
  replicas: {{ .Values.services.adminServer.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.services.adminServer.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.adminServer.name }}
    spec:
      containers:
        - name: admin-server
          image: {{ .Values.services.adminServer.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.services.adminServer.containerPort }}

---
apiVersion: v1
kind: Service
metadata:
  name: admin-server
spec:
  selector:
    app: admin-server
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.services.adminServer.containerPort }}
      targetPort: {{ .Values.services.adminServer.containerPort }}
