# customers-service.yaml
apiVersion: v1
kind: Pod
metadata:
  name: customers-service
  labels:
    app: {{ .Values.services.customersService.name }}
spec:
  containers:
    - name: customers-service
      image: {{ .Values.services.customersService.image }}
      imagePullPolicy: Always
      ports:
        - containerPort: {{ .Values.services.customersService.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: customers-service
spec:
  selector:
    app: customers-service
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.services.customersService.containerPort }}
      targetPort: {{ .Values.services.customersService.containerPort }}
