apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
spec:
  replicas: {{ .Values.services.discoveryServer.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.services.discoveryServer.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.discoveryServer.name }}
    spec:
      containers:
        - name: discovery-server
          image: {{ .Values.services.discoveryServer.image }}:{{ .Values.services.discoveryServer.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.services.discoveryServer.containerPort }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}

---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
spec:
  selector:
    app: discovery-server
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.services.discoveryServer.containerPort }}
      targetPort: {{ .Values.services.discoveryServer.containerPort }}
