apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits-service
spec:
  replicas: {{ .Values.services.visitsService.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.services.visitsService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.visitsService.name }}
    spec:
      containers:
        - name: visits-service
          image: {{ .Values.services.visitsService.image }}:{{ .Values.services.visitsService.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.services.visitsService.containerPort }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}

---
apiVersion: v1
kind: Service
metadata:
  name: visits-service
spec:
  selector:
    app: visits-service
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.services.visitsService.containerPort }}
      targetPort: {{ .Values.services.visitsService.containerPort }}
