apiVersion: v1
kind: Pod
metadata:
  name: vets-service
  labels:
    app: vets-service
spec:
  containers:
    - name: vets-service
      image: springcommunity/spring-petclinic-vets-service
      imagePullPolicy: Always
      env:
      - name: SPRING_PROFILES_ACTIVE
        value: docker,mysql
      - name: spring.jpa.properties.hibernate.dialect
        value: org.hibernate.dialect.MySQLDialect
      - name: spring.jpa.hibernate.ddl-auto
        value: update
      - name: spring.datasource.url
        value: jdbc:mysql://localhost:3306/petclinic?useSSL=false
      - name: spring.datasource.username
        value: root
      - name: spring.datasource.password
        value: petclinic
      ports:
        - containerPort: 8083

---
apiVersion: v1
kind: Service
metadata:
  name: vets-service
spec:
  selector:
    app: vets-service
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8083
      targetPort: 8083
