name: Build and Push Docker Images

on:
  push:
    branches:
      - main
      - develop
      - feature/Gitops

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: 'eu-west-3'
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install -P springboot

      - name: Run Unit Tests
        run: mvn test

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker images
        run: |
          services=("spring-petclinic-admin-server" "spring-petclinic-customers-service" "spring-petclinic-vets-service" "spring-petclinic-visits-service" "spring-petclinic-config-server" "spring-petclinic-discovery-server" "spring-petclinic-api-gateway")
          for service in "${services[@]}"
          do
            docker build -t $ECR_REPOSITORY/$DOCKER_IMAGE_PREFIX/$service:${{ github.sha }} ./spring-petclinic-$service
            docker push $ECR_REPOSITORY/$DOCKER_IMAGE_PREFIX/$service:${{ github.sha }}
          done
